services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://admin:secret123@db:5432/devopsdb
      - FLASK_DEBUG=1
    depends_on:
      db:
        condition: service_healthy
    command: python server.py

  checker:
    build: .
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://admin:secret123@db:5432/devopsdb
    depends_on:
      db:
        condition: service_healthy
    command: python runner.py

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=devopsdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret123
    ports:
      - "5432:5432"
    volumes:
      - uptime-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d devopsdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  uptime-pgdata:
